name: midterm_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  http: ^1.2.1
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.5
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

